export const NEW_USER = "NEW_USER"
//export const ADD_TO_EXISTING_USER = "ADD_TO_EXISTING_USER"
export const ACTIVE_INTERLOCUTOR = "ACTIVE_INTERLOCUTOR"
export const ADD_INTERLOCUTOR_MESSAGE = 'ADD_INTERLOCUTOR_MESSAGE'